
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 06 09:40:24 COT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 9;
  public static final int SUMA = 3;
  public static final int MULT = 5;
  public static final int EOF = 0;
  public static final int PYC = 2;
  public static final int ID = 8;
  public static final int DIV = 6;
  public static final int IGUAL = 7;
  public static final int error = 1;
  public static final int RESTA = 4;
}

